language: scala
scala:
  - 2.9.1
before_script:
  - sudo gem install jeweler
script: 
  - rake build
  - sudo gem install pkg/scala-bootstrapper-*.gem
  - mkdir birdname && cd birdname
  - scala-bootstrapper birdname
  - sbt update test
